import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ArrowRight, ArrowUpRight, Bell, Check, ClipboardList, HelpCircle, MapPin, Plus, RefreshCw } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { Button } from '@/components/ui/button';

type Filter='all'|'open'|'resolved';
const pageSize=12;
export default function BuyerDashboard(){
  const {user}=useAuth();const navigate=useNavigate();
  const [filter,setFilter]=useState<Filter>('all');const [page,setPage]=useState(0);
  const {data,error,isLoading,isFetching,refetch}=useQuery({queryKey:['customer-requests',user?.id,filter,page],enabled:!!user,retry:false,refetchInterval:30000,queryFn:async()=>{
    const claim=await supabase.rpc('claim_customer_leads');if(claim.error)throw new Error('Verify your email to access requests posted with that address.');
    const select='id,category,status,archived,created_at,location_text';
    let list=supabase.from('leads').select(select,{count:'exact'}).eq('customer_user_id',user!.id);
    if(filter==='open')list=list.eq('archived',false).in('status',['new','contacted']);
    if(filter==='resolved')list=list.or('archived.eq.true,status.in.(won,lost)');
    const [requests,all,open,resolved]=await Promise.all([
      list.order('created_at',{ascending:false}).order('id',{ascending:false}).range(page*pageSize,page*pageSize+pageSize-1),
      supabase.from('leads').select('id',{count:'exact',head:true}).eq('customer_user_id',user!.id),
      supabase.from('leads').select('id',{count:'exact',head:true}).eq('customer_user_id',user!.id).eq('archived',false).in('status',['new','contacted']),
      supabase.from('leads').select('id',{count:'exact',head:true}).eq('customer_user_id',user!.id).or('archived.eq.true,status.in.(won,lost)'),
    ]);
    if([requests,all,open,resolved].some(result=>result.error))throw new Error('Unable to load your requests. Please try again.');
    return {requests:requests.data ?? [],total:requests.count ?? 0,counts:{all:all.count ?? 0,open:open.count ?? 0,resolved:resolved.count ?? 0}};
  }});
  const suggestions=useQuery({queryKey:['customer-service-suggestions'],queryFn:async()=>{
    const {data,error}=await supabase.from('service_categories').select('id,name,slug,icon').eq('is_active',true).order('sort_order').limit(4);
    if(error)throw new Error('Service suggestions are unavailable.');return data ?? [];
  }});
  useEffect(()=>{ if(data && page>0 && page*pageSize>=data.total)setPage(Math.max(0,Math.ceil(data.total/pageSize)-1)); },[data,page]);
  const changeFilter=(value:Filter)=>{setFilter(value);setPage(0);};
  return <div className="min-h-screen bg-[#f5f6f8]">
    <a href="#customer-content" className="sr-only focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-50 focus:bg-white focus:p-3">Skip to requests</a>
    <header className="sticky top-0 z-30 border-b bg-white/95 backdrop-blur-xl"><nav aria-label="Customer navigation" className="max-w-7xl mx-auto px-5 lg:px-8 h-20 flex justify-between items-center gap-4"><Link to="/" className="text-2xl font-extrabold tracking-tight">FLEXS<span className="text-orange-600">.</span></Link><div className="flex items-center gap-3 sm:gap-6 text-sm"><Link to="/my-requests" aria-current="page" className="hidden sm:block font-semibold">My requests</Link><Link to="/customer-notifications" className="size-10 sm:w-auto flex justify-center items-center gap-2 rounded-xl hover:bg-muted" aria-label="Customer notifications"><Bell className="size-4" /><span className="hidden sm:inline">Notifications</span></Link><Link to="/support" className="size-10 sm:w-auto flex justify-center items-center gap-2 rounded-xl hover:bg-muted" aria-label="Customer support"><HelpCircle className="size-4" /><span className="hidden sm:inline">Support</span></Link></div></nav></header>
    <main id="customer-content" className="max-w-7xl mx-auto px-5 lg:px-8 py-8 lg:py-12 space-y-7">
      <div className="flex flex-wrap justify-between items-start gap-5"><div><p className="text-[10px] text-orange-700 font-semibold uppercase tracking-[0.18em]">Your customer workspace</p><h1 className="text-3xl sm:text-4xl font-semibold tracking-tight mt-3">Your requests</h1><p className="text-sm text-muted-foreground mt-3">Keep the details, quotes, and conversations for every project together.</p></div><Button asChild className="rounded-xl h-11"><Link to="/post-job"><Plus className="size-4 mr-2" />Place new request</Link></Button></div>
      <div className="rounded-2xl bg-primary text-white p-6 flex flex-wrap justify-between gap-5 items-center"><div><h2 className="font-semibold">Your project. Your choice.</h2><p className="text-xs text-white/70 mt-2 leading-relaxed">Compare quotes, ask questions, and choose the professional that works for you.</p></div><Link to="/help/customer-responses" className="text-xs font-semibold flex items-center gap-2">How it works <ArrowUpRight className="size-4" /></Link></div>
      <section aria-label="Request overview" className="grid grid-cols-3 gap-3 sm:gap-5">{[{key:'all' as const,label:'All requests',icon:ClipboardList},{key:'open' as const,label:'Open projects',icon:RefreshCw},{key:'resolved' as const,label:'Resolved projects',icon:Check}].map(({key,label,icon:Icon})=><button key={key} onClick={()=>changeFilter(key)} aria-pressed={filter===key} className={`text-left bg-white rounded-2xl border p-4 sm:p-6 hover:border-primary/40 ${filter===key ? 'border-primary/40' : ''}`}><Icon className="size-5 text-primary mb-4" /><p className="text-2xl sm:text-3xl font-semibold">{isLoading || error ? '—' : data?.counts[key] ?? 0}</p><p className="text-[11px] sm:text-sm text-muted-foreground mt-1">{label}</p></button>)}</section>
      <section className="space-y-5"><div className="flex flex-wrap justify-between gap-3 items-center"><div role="group" aria-label="Filter customer requests" className="inline-flex rounded-xl border bg-white p-1">{(['all','open','resolved'] as const).map(value=><button key={value} aria-pressed={filter===value} onClick={()=>changeFilter(value)} className={`px-4 py-2 text-xs font-medium rounded-lg ${filter===value ? 'bg-primary text-white' : 'text-muted-foreground hover:bg-muted'}`}>{value==='all' ? 'All projects' : value==='open' ? 'Open' : 'Resolved'}</button>)}</div><Button variant="outline" className="bg-white" aria-label="Refresh customer requests" disabled={isFetching} onClick={()=>void refetch()}><RefreshCw className={`size-3.5 mr-2 ${isFetching ? 'animate-spin' : ''}`} />Refresh</Button></div>
        {isLoading ? <div role="status" className="rounded-2xl border bg-white p-8 text-muted-foreground">Loading your requests…</div> : error ? <div role="alert" className="border rounded-2xl bg-white p-6"><p>{error.message}</p><Button variant="outline" className="mt-4" onClick={()=>void refetch()}>Retry requests</Button></div> : data?.requests.length ? <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{data.requests.map(request=>{
          const status=request.archived ? 'Closed request' : request.status==='won' ? 'Professional chosen' : request.status==='lost' ? 'No longer open' : 'Open for responses';
          return <article key={request.id} className="bg-white rounded-2xl border p-5 sm:p-6 flex flex-col"><div className="flex justify-between gap-3 items-center"><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${request.archived || ['won','lost'].includes(request.status) ? 'bg-muted text-muted-foreground' : 'bg-emerald-50 text-emerald-800'}`}>{status}</span><span className="text-xs text-muted-foreground">{formatDistanceToNow(new Date(request.created_at),{addSuffix:true})}</span></div><h2 className="text-lg font-semibold mt-6">{request.category}</h2><p className="text-sm text-muted-foreground mt-2 flex items-start gap-2"><MapPin className="size-4 shrink-0 mt-0.5" />{request.location_text}</p><p className="text-xs text-muted-foreground leading-relaxed mt-5 mb-6">{request.archived ? 'Your existing conversations are still available.' : request.status==='won' ? 'View the accepted quote and follow up with your professional.' : 'View professional responses, compare quotes, and discuss your project.'}</p><Button variant="outline" className="w-full mt-auto rounded-xl" onClick={()=>navigate(`/my-requests/${request.id}`)}>View request <ArrowRight className="size-4 ml-2" /></Button></article>;
        })}</div> : <div className="bg-white border rounded-2xl p-10 text-center"><ClipboardList className="size-10 text-muted-foreground mx-auto mb-4" /><h2 className="font-semibold">{filter==='all' ? 'Your next project starts here.' : `No ${filter} requests.`}</h2><p className="text-sm text-muted-foreground mt-2 mb-5">{filter==='all' ? 'Tell us what you need to start receiving professional responses.' : 'Try another filter to view your other projects.'}</p>{filter==='all' ? <Button asChild><Link to="/post-job">Place your first request</Link></Button> : <Button variant="outline" onClick={()=>changeFilter('all')}>Show all projects</Button>}</div>}
        {data && data.total>pageSize && <nav aria-label="Customer request pages" className="flex flex-wrap justify-center items-center gap-4"><Button variant="outline" disabled={page===0} onClick={()=>setPage(v=>v-1)}>Previous requests</Button><span className="text-xs text-muted-foreground">Page {page+1} of {Math.ceil(data.total/pageSize)}</span><Button variant="outline" disabled={(page+1)*pageSize>=data.total} onClick={()=>setPage(v=>v+1)}>Next requests</Button></nav>}
      </section>
      <section className="border-t pt-8"><div className="flex justify-between items-center gap-4 mb-5"><h2 className="text-xl font-semibold">What else is on your list?</h2><Link to="/post-job" className="text-xs font-semibold inline-flex gap-2 items-center">All services <ArrowRight className="size-3.5" /></Link></div>{suggestions.isLoading ? <p role="status" className="text-sm text-muted-foreground">Loading services…</p> : suggestions.error ? <div role="alert"><p className="text-sm text-muted-foreground">Service suggestions could not be loaded. Your requests remain available.</p><Button variant="outline" className="mt-3" onClick={()=>void suggestions.refetch()}>Retry suggestions</Button></div> : <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{suggestions.data?.map(category=><Link key={category.id} to={`/services/${category.slug}`} className="bg-white border rounded-2xl p-5 hover:border-primary/40"><div className="size-10 grid place-items-center rounded-xl bg-primary/5 text-xl">{category.icon || <ClipboardList className="size-5" />}</div><h3 className="text-sm font-semibold mt-4">{category.name}</h3><p className="text-xs text-muted-foreground mt-2">Explore service</p></Link>)}</div>}</section>
      <footer className="pt-6 border-t text-xs text-muted-foreground flex flex-wrap justify-between gap-4"><p>FLEXS · Independent marketplace</p><Link to="/pro" className="inline-flex gap-1.5 items-center">For professionals <ArrowUpRight className="size-3" /></Link></footer>
    </main>
  </div>;
}
