import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Search, ArrowRight } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';

const articles=[
  {slug:'post-request',title:'How do I request quotes?',body:'Choose a service, answer the questions, and submit your contact details and location. Posting a request is free. Sign in with the same email and confirm it to see your request, compare quotes, and speak privately with professionals.',to:'/post-job',label:'Post a request'},
  {slug:'customer-responses',title:'How do I manage my request?',body:'Open My requests to view an existing request. You can reply to professionals who unlocked your contact, compare their quotes, accept one quote, or close the request. Closing stops new contact unlocks while keeping existing conversations available.',to:'/my-requests',label:'My requests'},
  {slug:'credits',title:'How do professional credits work?',body:'Credits let professionals unlock a customer’s contact details. You can browse a privacy-protected preview first. The cost is shown on the request, and repeating the same unlock does not charge twice. Credit packages are priced in Canadian dollars. Your balance updates after payment is confirmed.',to:'/app/settings/credits',label:'Your credits'},
  {slug:'credit-refunds',title:'How do I request a credit refund?',body:'Open a request you unlocked and use the credit refund form to explain the issue. The team reviews requests individually. An approved request returns lead credits to your wallet; it is not a bank-card refund. If you cannot access the request, create a support ticket with its reference.',to:'/app/responses',label:'Your unlocked requests'},
  {slug:'verified',title:'What is a verified customer review?',body:'A verified FLEXS customer review comes from the confirmed-email owner of a request who accepted that professional’s quote. The customer can publish one review from their request. Professionals cannot delete verified reviews. This verifies the customer relationship; it does not certify completed work, qualifications, or licensing.',to:'/my-requests',label:'Open your request'},
  {slug:'notifications',title:'How do reminders and notifications work?',body:'Create a follow-up reminder from a request or the Reminders screen. Due reminders and unread updates refresh while the professional app is open. You can turn message and reminder notifications on or off in Settings. Existing notices stay available. Email, SMS, and device push are not currently enabled.',to:'/app/reminders',label:'Your reminders'},
  {slug:'account-access',title:'How do I reset my password or change my email?',body:'Use Forgot your password on the login page to request an email reset link. Choose a new password using that link; your sessions are signed out after the change. Account settings let you update your account name and request a confirmed email change. Your public business email is managed separately in your profile.',to:'/auth/forgot-password',label:'Reset your password'},
  {slug:'contact-support',title:'How do I contact FLEXS support?',body:'Sign in and create a private support ticket. You can follow the conversation, reply, and close or reopen your ticket. Only your account and authorized FLEXS administrators can read it. Include the request or transaction reference when it helps explain your issue. Response times depend on the team’s availability.',to:'/support',label:'Create a support ticket'},
  {slug:'privacy',title:'How do I request account deletion or my data?',body:'Create a support ticket and choose Account deletion or data request. The team will review the request and confirm the next steps. Creating a ticket does not immediately delete your account, requests, credits, or data.',to:'/support',label:'Create a data request'},
];
export default function HelpCenter(){
  const {slug}=useParams();const [search,setSearch]=useState('');
  const selected=articles.find(article=>article.slug===slug);
  const visible=articles.filter(article=>`${article.title} ${article.body}`.toLowerCase().includes(search.trim().toLowerCase()));
  return <div className="min-h-screen bg-background"><header className="border-b"><nav className="max-w-6xl mx-auto px-5 py-4 flex flex-wrap justify-between gap-4"><Link to="/" className="font-bold text-xl text-primary">FLEXS</Link><div className="flex gap-5 text-sm items-center"><Link to="/help">Help centre</Link><Link to="/support">Support tickets</Link><Link to="/app/dashboard">Professional dashboard</Link></div></nav></header>
    <main className="max-w-5xl mx-auto px-5 py-10 space-y-7">{slug ? selected ? <article className="max-w-3xl space-y-5"><Link to="/help" className="text-sm text-primary">All help topics</Link><h1 className="text-3xl font-bold">{selected.title}</h1><p className="text-muted-foreground leading-relaxed">{selected.body}</p><Button asChild><Link to={selected.to}>{selected.label}<ArrowRight className="h-4 w-4 ml-2" /></Link></Button></article> : <div className="space-y-4"><h1 className="text-2xl font-bold">This help topic is unavailable</h1><p className="text-muted-foreground">Choose a current help topic or create a support ticket.</p><Button asChild><Link to="/help">Browse help topics</Link></Button></div> : <><h1 className="text-3xl font-bold">How can we help?</h1><p className="text-muted-foreground">Guides for customers and professionals using FLEXS.</p><div className="relative"><Search className="absolute left-3 top-3 h-5 w-5 text-muted-foreground" /><Input className="pl-10" aria-label="Search help topics" placeholder="Search requests, credits, reviews, or account access" value={search} onChange={e=>setSearch(e.target.value)} /></div><div className="grid md:grid-cols-2 gap-4">{visible.map(article=><Link key={article.slug} to={`/help/${article.slug}`} className="border rounded-xl p-5 hover:border-primary"><h2 className="font-semibold">{article.title}</h2><p className="text-sm text-muted-foreground mt-2 line-clamp-2">{article.body}</p></Link>)}</div>{!visible.length && <p className="text-muted-foreground">No help topics match. Create a support ticket for more help.</p>}</>}
      <section className="border rounded-xl bg-primary/5 p-5 flex flex-wrap justify-between gap-4 items-center"><div><h2 className="font-semibold">Need help with your account?</h2><p className="text-sm text-muted-foreground mt-1">Follow your request in a private support conversation.</p></div><Button asChild variant="outline"><Link to="/support">Open support</Link></Button></section>
    </main></div>;
}
